name: CI

on:
  # Only run push on master
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '*.md'
  # Always run on PRs
  pull_request:

jobs:
  build:
    name: JDK ${{ matrix.java_version }}
    runs-on: macOS-latest
    strategy:
      matrix:
        java_version: [11]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v4.3.0
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java_version }}
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v3.5.0
      - name: Cache gradle packages
        uses: actions/cache@v4.0.2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.7
      - name: Configure Gradle
        run: ./gradlew help
      - name: Check formatting
        run: ./gradlew spotlessCheck --stacktrace
      - name: Build project
        run: ./gradlew assemble --stacktrace
      # TODO split test and instrumentation into parallel builds
      - name: Run tests
        run: ./gradlew test --stacktrace
      - name: Run instrumentation tests
        uses: malinskiy/action-android/emulator-run-cmd@release/0.1.7
        with:
          cmd: ./gradlew connectedCheck --stacktrace
          api: 30
          tag: default
          abi: x86
      - name: Full check
        run: ./gradlew check --stacktrace
      - uses: actions/upload-artifact@v4
        with:
          name: Sample App
          path: sample/build/outputs
