name: CI

on: [push, pull_request]

jobs:
  build:
    name: JDK ${{ matrix.java_version }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./android
    strategy:
      matrix:
        # TODO Add 9, 10, 11, 12, and 13 after Kotlin 1.3.60
        java_version: [11]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java_version }}
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.1
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1
      - name: Configure Gradle
        # Gradle configuration install deps
        run: ./gradlew help
      - name: Spot check
        run: ./gradlew spotlessCheck --stacktrace
      - name: Build Project
        run: ./gradlew assemble --stacktrace
      - name : Testing
        run: ./gradlew test --stacktrace
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script:
            ./gradlew connectedCheck
      - name: Final Checks
        run: ./gradlew check --stacktrace