name: Release documentation

on:
  release:
    types: [published]

jobs:
  documentation:
    name: Dokka
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Install JDK 11
        uses: actions/setup-java@v4.3.0
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v3.5.0
      - name: Cache gradle packages
        uses: actions/cache@v4.0.2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.7
      - name: Configure Gradle
        run: ./gradlew help
      - uses: actions/setup-python@v5.2.0
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            mkdocs
            mkdocs-material
      - name: Generate dokka
        run: ./gradlew dokka
      - name: Add plain files
        run: |
          cp README.md docs/index.md
          cp CHANGELOG.md docs/changelog.md
          cp CONTRIBUTING.md docs/contributing.md
          cp CODE_OF_CONDUCT.md docs/code-of-conduct.md
          cp RELEASING.md docs/releasing.md
      - name: Build & deploy
        run: mkdocs gh-deploy --force
